---
- name: Playbook with Precheck Role
  hosts: eos

  tasks:
  - name: Precheck block
    block:
      - name: Import the precheck role
        import_role:
          name: precheck
    rescue:
      - fail:
          msg: "Precheck failed. Rolling back"

